### ISSUE TITLE
Peer Review #2

### ISSUE THREAD

**Issue by mushroomcarbon** [hoodiexxx/lol_player_KDA_prediction#2]
Summary
The paper utilizes a Bayesian model to predict the KDA, an metric for overall performance, of the professional League of Legends players playing for the team BLG using predictor variables such as vision score, total gold, and damage to champions. Other models are also used, with analysis contrasting their performance with and explaining why they were dropped in favour of a Bayesian model, and further analysis in the context of the dataset is also given.

Strong positive points:
Figure 1 is _phenomenal_
Great usage of multiple models to compare and contrast the predictive abilities of each one before settling on your final choice (as compared to, for example, just choosing a Bayesian one without any explanation/evidence as to why so)
Love how there are multiple graphs showcasing the different aspects of one model such as residuals, credible intervals, etc.

Critical improvements needed ([just passing by dont mind me](https://media.istockphoto.com/id/94929126/photo/avocados-isolated-on-white.jpg?s=612x612&w=0&k=20&c=c0BSuWnUTAkZyj-cYHKzR5dXtZWQ1_3PXcea3M92Z4I=)):
Regarding the model, while it's definitely a strong model overall, there's a couple questions that I'm left with as a reader. Why is KDA chosen as your performance metric of choice rather than winrate, for example, and why are totalgold and totalcs linearly predictive factors while position follows a random normal distribution? 

More in-depth explanation regarding your decision-making process and how conclusions are reached could also be helpful for readers. For example, why is ON recording the highest vision scores across games _expected_ due to him being a support in section 2.4.2? Personally I would have preferred to have a source that I can check up on to confirm this information, or maybe potentially an analysis done on the data given that compares the vision scores of support players compared to everyone else. Additionally, tying into the last bit, it seems that ON's vision score is expected to be higher than that of his teammates by virtue of him taking on a more supportive role in-game - this suggests that a potential modifier could be put in place for ON that reduces the predictive effect of his higher vision score on his overall performance compared to the other members of the team. For cases like these, I'm sure you have your informed reasons as for why/why not a decision was made, but as a reader I feel like it would have been nice if some of this rationale could have been shared with us in the paper just a tad more.

Additionally, the content in section 2.4.1 seems just a little out-of-context and out-of-place to me. Context regarding terminology such as top lane, Renekton, and utility vs. engage-heavy champions isn't really presented to the reader and neither are sources, which means that reading through this, I need to search up information alongside the paper to be able to understand the paper. The data talked about in this section also, more importantly, seems to not be used anywhere else in the paper, which makes it seem as if the insights are off on a tangent, potentially.

Suggestions for improvement:
While the prose of the paper is generally excellent, there are still a couple minor typos and mistakes such as lack of capitalisation and improper word spacing in the paper, which may be distracting from the rest of the paper. Nothing a quick run through GPT/grammarly won't solve though, so nothing major of course.

I see you referring to Elk as both bot lane and ADC whereas other players seemingly only have one distinction in their role - the use of terminology here could be explained quickly maybe just by adding a small statement about how the terms are interchangeable (or not, depending on the context).

While each individual graph looks quite nice for the most part, I couldn't help noticing the stylistic differences between the various graphs, especially regarding colour - the specific colour codes seem to be different across all the graphs, i.e. the blue that I just saw in Figure 2 isn't quite the blue that I saw in Figure 4 (at least just from an eye test). More cohesion on this aspect could potentially make the graphs look even better than now.

With figure 4b specifically, is there another way to graph the data points that make then look a bit more separated from each other? Some of the lines seem to be blurring into each other and are hard to discern from each other sometimes.

Page 14 also has a big chunk of unused space. Visually I feel like fitting in a figure or two, or maybe just sending the next section up into this space might be a better utilisation of space in the paper.

The title of Figure 7 is too long and doesn't show fully. Small issues in general, just a quick fix will do ([a combination of strwrap and paste, for example](https://stackoverflow.com/questions/2631780/set-the-plot-title-to-wrap-around-and-shrink-the-text-to-fit-the-plot)).

Evaluation:

R/Python cited (1/1)
Done.
Data cited (1/1)
Done.
Class paper (1/1)
Done.
LLM documentation (1/1)
Done.
Title (1/2)
Does not include what happens at the end (i.e. results).
Author, date, and repo (2/2)
Present.
Abstract (3/4)
Same as with the title - results and insights coming from the model are not included.
Introduction (3/4)
Same as above, other parts of the introduction are really strong though.
Estimand (1/1)
Present.
Data (7/10)
Variables of interest are touched upon, but so are variables that are not of interest. Relatively extraneous information can be better placed in the Appendix, for example.
Measurement (4/4)
Great. Would have liked a brief explanation of _why_ oracleselixir's dataset is "widely considered as reliable within the esports analytics community", but at this point I'm just nitpicking (probably). 
Model (6/10)
Good, but the lack of communication regarding crucial design choices leaves quite a lot to be desired.
Results (7/10)
Good results section, but the insights on Bin following up from the data on him from the model is better left in the discussion section rather than here.
Discussion (6/10)
Interesting read, but lacks a bit of context in section 5.2. How much of a higher contract does Bin have than Elk, for example? I also don't have much knowledge on how in-game priority or Bin's negative impact on team performance are really quantified or understood.
Prose (2/6)
The way the text is written is generally good but there are a tad bit too many minor mistakes (grammatical, punctuation, formatting etc).
Cross-references (1/1)
Present.
Captions (1/2)
Fig. 9: Again I'm not quite aware of Bin's superstar status in the team before this - throwing this in a caption right here inevitably feels a bit abrupt.
Graphs/tables/etc (2/4)
Figure 4b is cluttered, and the text in the guide for Figure 1 is tiny
Surveys, sampling, and observational data appendix (6/10)
A more in-depth dive into methodology would have been appreciated, as the current state of section B.3 doesn't show your knowledge about sampling and surveying techniques quite enough. 
Referencing (4/4)
References often go in the Data section if I remember correctly, not sure if that's an issue per se though.
Commits (2/2)
Solid.
Sketches (2/2)
Present.
Simulation (3/4)
Good.
Tests (3/4)
Good.
Parquet (1/1)
Done.
Reproducible workflow (4/4)
Clean comments. I _think_ renv isn't supposed to be in here, though? Needs confirmation.
Enhancements (2/4)
Done.
Miscellaneous (2/3)
Interesting read and choice of topic.
Estimated overall mark:
83 out of 112.
Any other comments:
Overall solid paper! Interesting read with lots of content to run through.

**Comment by hoodiexxx** [comment]
"Regarding the model, while it's definitely a strong model overall, there's a couple questions that I'm left with as a reader. Why is KDA chosen as your performance metric of choice rather than winrate, for example, and why are totalgold and totalcs linearly predictive factors while position follows a random normal distribution?" -  just add win rate prediction model by logistic regression in the appendix

Why is KDA chosen as your performance metric of choice rather than winrate, for example, and why are totalgold and totalcs linearly predictive factors while position follows a random normal distribution?  -   why chosen normal distribution as we believe the prior distribution for totalgold and totalcs is follow normal distribution in the dataset.

Additionally, tying into the last bit, it seems that ON's vision score is expected to be higher than that of his teammates by virtue of him taking on a more supportive role in-game - this suggests that a potential modifier could be put in place for ON that reduces the predictive effect of his higher vision score on his overall performance compared to the other members of the team.  - since we use position as a random effect in bayesian model, different position has different baseline.

While each individual graph looks quite nice for the most part, I couldn't help noticing the stylistic differences between the various graphs, especially regarding colour - the specific colour codes seem to be different across all the graphs, i.e. the blue that I just saw in Figure 2 isn't quite the blue that I saw in Figure 4 (at least just from an eye test). More cohesion on this aspect could potentially make the graphs look even better than now. - the R code color assign logic is base on the playername in alphebetic colour, so the colour actually are the same even I didn't sepcify the color code. 

The title of Figure 7 is too long and doesn't show fully. Small issues in general, just a quick fix will do ([a combination of strwrap and paste, for example](https://stackoverflow.com/questions/2631780/set-the-plot-title-to-wrap-around-and-shrink-the-text-to-fit-the-plot)).  - just adjust the title for figure 7.

Thanks for your review.
